/**
 * Project Management Application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TicketDetailsDTO } from 'ticketDetailsDTO';


export interface TicketDTO { 
    id?: any;
    name?: any;
    ticketType?: any;
    dateCreated?: any;
    dateUpdated?: any;
    status?: any;
    resolution?: any;
    userRole?: any;
    ticketDetails?: any;
}

