/**
 * Project Management Application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TicketDTO } from 'ticketDTO';


export interface UsersDTO { 
    id?: any;
    userName?: any;
    email?: any;
    password?: any;
    appUserRole?: UsersDTO.AppUserRoleEnum;
    ticketList?: any;
}
export namespace UsersDTO {
    export type AppUserRoleEnum = 'USER' | 'ADMIN';
    export const AppUserRoleEnum = {
        USER: 'USER' as AppUserRoleEnum,
        ADMIN: 'ADMIN' as AppUserRoleEnum
    };
}


