# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_DATABASE: pms 
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  back-end:
    image: pma-app:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/pms?enabledTLSProtocols=TLSv1.2

  front-end:
    image: pma-web:latest
    depends_on:
      - back-end
    ports:
      - 4200:80